name: validasi_ide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  gal: ^2.3.3
  geocoding: ^3.0.0
  geolocator: ^14.0.3
  go_router: ^17.5.0
  google_fonts: ^8.2.1
  image_picker: ^1.2.3
  intl: ^0.20.3
  latlong2: ^0.10.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.17.2
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/market_mind_logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
